### ISSUE TITLE
Invalid profile name triggers an exception

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#104]
```
Traceback (most recent call last):
  File "/home/creffett/.local/bin/statick", line 39, in <module>
    main()
  File "/home/creffett/.local/bin/statick", line 26, in main
    issues, success = statick.run(path, parsed_args)
  File "/home/creffett/.local/lib/python2.7/site-packages/statick_tool/statick.py", line 119, in run
    level = self.get_level(path, args)
  File "/home/creffett/.local/lib/python2.7/site-packages/statick_tool/statick.py", line 96, in get_level
    profile = Profile(self.resources.get_file(profile_filename))
  File "/home/creffett/.local/lib/python2.7/site-packages/statick_tool/profile.py", line 11, in __init__
    with open(filename) as fname:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Should catch this and print a more descriptive error message.

**Comment by creffett** [comment]
Fixed in #105
