### ISSUE TITLE
Regex failed

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#229]
When trying to add an exception for a file we got the following Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/statick_ws", line 163, in <module>
    main()
  File "/usr/local/bin/statick_ws", line 96, in main
    issues, dummy = statick.run(package[1], parsed_args)
  File "/usr/local/lib/python3.5/dist-packages/statick_tool/statick.py", line 304, in run
    issues = self.exceptions.filter_issues(package, issues)
  File "/usr/local/lib/python3.5/dist-packages/statick_tool/exceptions.py", line 188, in filter_issues
    issues = self.filter_regex_exceptions(exceptions["message_regex"], issues)
  File "/usr/local/lib/python3.5/dist-packages/statick_tool/exceptions.py", line 142, in filter_regex_exceptions
    compiled_re = re.compile(exception_re)  # type: Pattern
  File "/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

The regex that was used was similar to `"*string*"`.

**Comment by denewiler** [comment]
Fixed by #230.
