### ISSUE TITLE
CCCC not subscriptable error

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#410]
While checking a package a user reported the following crash in the CCCC plugin.

```shell
NFO:root:Running cccc tool plugin...
Traceback (most recent call last):
  File "/home/user/.local/bin/statick", line 50, in <module>
    main()
  File "/home/user/.local/bin/statick", line 39, in main
    success = run(statick, parsed_args)
  File "/home/user/.local/bin/statick", line 14, in run
    issues, success = statick.run(path, parsed_args)
  File "/home/user/.local/lib/python3.8/site-packages/statick_tool/statick.py", line 395, in run
    tool_issues = plugin.scan(package, level)
  File "/home/user/.local/lib/python3.8/site-packages/statick_tool/plugins/tool/cccc_tool_plugin.py", line 90, in scan
    issues: List[Issue] = self.parse_output(tool_output, package, config_file)
  File "/home/user/.local/lib/python3.8/site-packages/statick_tool/plugins/tool/cccc_tool_plugin.py", line 103, in parse_output
    for module in output["CCCC_Project"]["structural_summary"]["module"]:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by denewiler** [comment]
This issue is not observed after #412 was merged.
