### ISSUE TITLE
Findbugs quietly failing due to argument handling problems

### ISSUE THREAD

**Issue by creffett** [sscpac/statick#45]
Running Statick in an Ubuntu 16.04 environment, I got the following backtrace when running with --show-tool-output:
```
Running findbugs tool plugin...
[warning] /usr/bin/findbugs: Unable to locate ant in /usr/share/java
The following errors occurred during analysis:
  File not found: filesystem:/home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/statick_output/dsat_jaus2ros_sensor-sei_cert/longBugCodes
  File not found: filesystem:/home/jenkins/workspace/ROSM_rtk-statick_master-XIVWAOJYVSYPP4AQ5FZIKKA755OLWXMYAKWA4FWMINIDWHGUV7YA/statick_output/dsat_jaus2ros_sensor-sei_cert/-include\
  Cannot open codebase filesystem:/usr/local/lib/python2.7/dist-packages/statick_tool/rsc/findBugs-security.xml
    java.io.IOException: Wrong magic bytes of 3c46696e for zip file /usr/local/lib/python2.7/dist-packages/statick_tool/rsc/findBugs-security.xml of 249 bytes
      At edu.umd.cs.findbugs.classfile.impl.ZipFileCodeBase.<init>(ZipFileCodeBase.java:87)
      At edu.umd.cs.findbugs.classfile.impl.ZipCodeBaseFactory.makeZipCodeBase(ZipCodeBaseFactory.java:39)
      At edu.umd.cs.findbugs.classfile.impl.ClassFactory.createFilesystemCodeBase(ClassFactory.java:121)
      At edu.umd.cs.findbugs.classfile.impl.FilesystemCodeBaseLocator.openCodeBase(FilesystemCodeBaseLocator.java:77)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.processWorkList(ClassPathBuilder.java:607)
      At edu.umd.cs.findbugs.classfile.impl.ClassPathBuilder.build(ClassPathBuilder.java:226)
      At edu.umd.cs.findbugs.FindBugs2.buildClassPath(FindBugs2.java:677)
      At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:218)
      At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
      At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
      At edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
      At edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)

Exception in thread "main" java.io.IOException: No files to analyze could be opened

	at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:276)
	at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:402)
	at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1200)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.launch(LaunchAppropriateUI.java:106)
	at edu.umd.cs.findbugs.LaunchAppropriateUI.main(LaunchAppropriateUI.java:198)
```

Looks like there's some issue with how the args are getting passed to findbugs, plus either findbugs isn't giving a "bad result" error code or we're ignoring it. Will investigate.

**Comment by creffett** [comment]
Fix was merged.
